name: Cron Test

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0

jobs:
  run-cron: render-crona.js
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "Cron job triggered"
