name: Run 8am 8pm pisstest

on:
  schedule:
    - cron: '0 8,20 * * *' # ← runs every hour on the hour
  workflow_dispatch:     # ← allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run pisstestdb.js
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: node scripts/pisstestdb.js
